### PR TITLE
Fix readthedocs configuration

### LINKED ISSUE #406: readthedocs deployment broken
The deployment of docs to readthedocs.org is broken with this error

```
No default configuration file found at repository's root.
```

Apparently RTD has changed the default requirements for builds

https://discuss.openedx.org/t/readthedocs-build-failures-missing-config-or-invalid-build-os/11871

### PR DESCRIPTION
**Pull request by aidanheerdegen**
Add readthedocs configuration file as this is now a requirement.

Configured RTD to run on PRs, so should get a status if this fix worked.

Fixes #406

### CODE REVIEW

**Comment by aidanheerdegen** [comment]
Well that seemed to have worked. The preview docs have been generated. Can you check the preview @jo-basevi to make sure it has your most recent updates?

**Comment by aidanheerdegen** [comment]
According to the RTD logs, the docs build too 29s, and it is being done on RTD hardware, so I don't think it is a problem to have this turned on routinely for PRs. It would have led to us noticing the builds were failing a lot sooner. Apparently this requirement was [turned on in September](https://blog.readthedocs.com/migrate-configuration-v2/).

**Comment by jo-basevi** [comment]
> Well that seemed to have worked. The preview docs have been generated. Can you check the preview @jo-basevi to make sure it has your most recent updates?

The previews have the most recent updates!

From what I can tell, the currently the docs show only the latest and stable version, is it possible to get previous versions e.g. `1.0.30`?

**Review by jo-basevi — APPROVED** [review]
LGTM

**Comment by aidanheerdegen** [comment]
> is it possible to get previous versions

It looks like it is possible, but would involve using branches and adding the config file to them

https://stackoverflow.com/questions/72324316/build-documentation-for-older-version-before-readthedocs-yaml-was-added-to-repo#comment128600046_72324316

We made a `1.0` branch so we could back-port bug fixes etc, so it would be relatively straightforward

https://github.com/payu-org/payu/tree/release/1.0

But we'd probably use a new tag to get the "old" version of the docs.

**Pull request merged**
