### PR TITLE
Update the list of config files used by WW3 in CESM models.

### PR DESCRIPTION
**Pull request by micaeljtoliveira**

### CODE REVIEW

**Comment by micaeljtoliveira** [comment]
@aidanheerdegen Any chance you could review this very small PR?

**Review by aidanheerdegen — APPROVED** [review]
LGTM

**Comment by aidanheerdegen** [comment]
I'll leave you to merge when you're ready @micaeljtoliveira

**Comment by micaeljtoliveira** [comment]
@aidanheerdegen I don't have permission to merge on this repo.

**Pull request merged**
