### PR TITLE
Fileinputs

### PR DESCRIPTION
**Pull request by marshallward**

### CODE REVIEW

**Comment by marshallward** [comment]
Working on a method using `os.walk` over files, at the insistence of Dr Heerdegen

**Comment by aidanheerdegen** [comment]
I should have left a nasty message in the PR totally slamming this code

**Review by aidanheerdegen — APPROVED** [review]
Nice.

**Comment by aidanheerdegen** [comment]
Just for future reference (when python2 support is dropped)
```python
def walkf(path):
    """
    Add to os.walk to return a file name if that is passed in
    """
    if os.path.isfile(path):
        path, fname = os.path.split(path)
        yield path, None, fname
    else:
        yield from os.walk(path)
```

**Pull request merged**
