### PR TITLE
Empty YAML config handled as empty dict

### PR DESCRIPTION
**Pull request by marshallward**
If one passes an empty YAML file, e.g. all lines commented out, then
PyYAML returns `None`, which breaks subsequent assumptions in the
handling of config.

We now parse an empty file as an empty dict, {}.

### CODE REVIEW

**Comment by aidanheerdegen** [comment]
Do we want to add a test to make sure this is picked up in case it gets accidentally removed/changed?

**Comment by marshallward** [comment]
Do you mean just adding a test case with an empty YAML file?  Yeah, I can add that.

But you may mean something more significant, which I am missing.

**Comment by aidanheerdegen** [comment]
Yeah I meant an empty yaml test. I don't think it is super important, but it is a good habit to get into to add to the tests when a bug is fixed.

**Comment by aidanheerdegen** [comment]
I noticed this was still open, do you still feel like adding an empty yaml file test case @marshallward?

**Comment by marshallward** [comment]
Seems I cannot even remember how to run the tests (or perhaps they have changed).  This may need a chat.

**Comment by aidanheerdegen** [comment]
@marshallward I added a test for an empty config, and found to my surprise it isn't empty because of that auto translation of the old `collate` boolean to a `dict`. 

Are you happy with this behaviour, or do you want some special case logic around this

https://github.com/payu-org/payu/blob/master/payu/fsops.py#L72-L91

**Comment by aidanheerdegen** [comment]
Sorry, had to rebase and force push for tests to be consistent with current code base.

**Comment by marshallward** [comment]
All good with me!

**Pull request merged**
