### PR TITLE
Nonsense whitespace change

### PR DESCRIPTION
**Pull request by aidanheerdegen**
Testing the pep8 bot

### CODE REVIEW

**Comment by aidanheerdegen** [comment]
@pep8speaks Suggest a diff

**Comment by aidanheerdegen** [comment]
@pep8speaks pep8ify

**Comment by aidanheerdegen** [comment]
@marshallward I was always forgetting to run `pycodestyle` before a PR, so I installed a pep8 bot. Look here if you want to make config changes

https://github.com/OrkoHunter/pep8speaks?installation_id=1102120&setup_action=install#configuration

Oddly it found the long line I put in, but the gist and PR fix something unrelated which isn't flagged. Odd.

**Comment by marshallward** [comment]
Looks cool, I will always support militant PEP8 enforcement.

I'd say that it will save me the trouble, but I have this feeling I won't be paying much attention to Payu for some time!

**Pull request closed without merging**
